kind: pipeline
name: developci

stages:
  - name: clone
    steps:
      - step:
        name: clone_code
        image: docker.easyops.local/ci/git_clone
        description: "clone code"
        category: source
        settings:
          recursive: true
          depth: 50
          skip_verify: true

  - name: publish
    steps:
      - name: publish_giraffe
        image: docker.easyops.local/ci/publish_contract
        description: "publish contract by go"
        category: publish
        settings:
          language: go
          service: all

volumes:
  - name: go-cache
    hostPath:
      path: /go-cache
